import { NextResponse } from "next/server";
import { getUserAccountContext } from "@/lib/accounts/account-context";
import {
  buildCalendarItems,
  buildWeeklyCampaigns,
  monthLabel,
} from "@/lib/content-calendar/monthly-plan";
import { createClient } from "@/lib/supabase/server";
import { untypedSupabase } from "@/lib/supabase/untyped";

export async function POST(request: Request) {
  const supabase = untypedSupabase(await createClient());

  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const accountContext = await getUserAccountContext({ supabase, userId: user.id });
  const activeAccountId = accountContext.activeAccountId;

  if (!activeAccountId) {
    return NextResponse.json({ error: "No active workspace selected." }, { status: 400 });
  }

  if (!accountContext.canManageActiveAccount) {
    return NextResponse.json({ error: "You do not have permission to create calendar plans for this workspace." }, { status: 403 });
  }

  const formData = await request.formData();

  const planMonthRaw = String(formData.get("plan_month") || "");
  const monthlyTheme = String(formData.get("monthly_theme") || "").trim();
  const businessGoal = String(formData.get("business_goal") || "").trim();
  const targetAudience = String(formData.get("target_audience") || "").trim();
  const offerFocus = String(formData.get("offer_focus") || "").trim();
  const primaryCta = String(formData.get("primary_cta") || "").trim();

  if (!planMonthRaw || !monthlyTheme) {
    return NextResponse.json(
      { error: "Plan month and monthly theme are required." },
      { status: 400 }
    );
  }

  const planMonth = `${planMonthRaw}-01`;
  const label = monthLabel(planMonth);
  const input = {
    planMonth,
    monthlyTheme,
    businessGoal,
    targetAudience,
    offerFocus,
    primaryCta,
  };

  const weeklyCampaigns = buildWeeklyCampaigns(input);

  const { data: plan, error: planError } = await supabase
    .from("content_calendar_plans")
    .insert({
      user_id: user.id,
      account_id: activeAccountId,
      plan_month: planMonth,
      month_label: label,
      monthly_theme: monthlyTheme,
      business_goal: businessGoal || null,
      target_audience: targetAudience || null,
      offer_focus: offerFocus || null,
      status: "planned",
      weekly_campaigns: weeklyCampaigns,
      notes:
        "Generated by the Strategic Content Calendar foundation. Creates one distinct campaign per week and supporting planned content items.",
    })
    .select("*")
    .single();

  if (planError || !plan) {
    return NextResponse.json(
      { error: planError?.message ?? "Unable to create content calendar plan." },
      { status: 400 }
    );
  }

  const items = buildCalendarItems(input, plan.id, user.id).map((item) => ({
    ...item,
    account_id: activeAccountId,
  }));

  const { data: createdItems, error: itemError } = await supabase
    .from("content_calendar_items")
    .insert(items)
    .select("*");

  if (itemError) {
    await supabase
      .from("content_calendar_plans")
      .delete()
      .eq("id", plan.id)
      .eq("account_id", activeAccountId);

    return NextResponse.json({ error: itemError.message }, { status: 400 });
  }

  await supabase.from("activity_log").insert({
    user_id: user.id,
    account_id: activeAccountId,
    activity_type: "content_calendar_plan_generated",
    title: "Strategic content calendar generated",
    description: `${label}: ${monthlyTheme}`,
    metadata: {
      planId: plan.id,
      planMonth,
      monthLabel: label,
      weeklyCampaignCount: weeklyCampaigns.length,
      itemCount: createdItems?.length ?? 0,
      monthlyTheme,
      businessGoal,
      targetAudience,
      offerFocus,
      accountId: activeAccountId,
      activeAccountName: accountContext.activeAccountName,
    },
  });

  return NextResponse.json({
    ok: true,
    plan,
    items: createdItems ?? [],
  });
}