import type { StrategyFieldContract, StrategyFieldKey } from "./types.ts";

export const STRATEGY_FIELD_CONTRACTS: Record<StrategyFieldKey, StrategyFieldContract> = {
  campaignObjective: { field: "campaignObjective", label: "Campaign objective", purpose: "Define the belief, decision, or commercial action the campaign should make more likely.", allowedSources: ["campaign goal", "promoted offer", "primary CTA"], forbiddenSources: ["brand slogan", "generic growth language", "vendor frustration"], requirements: ["one decision change", "commercial relevance", "clear connection to CTA"], minWords: 14, maxWords: 55 },
  targetAudience: { field: "targetAudience", label: "Target audience", purpose: "Identify one primary decision-maker, business context, and responsibility.", allowedSources: ["resolved audience", "buyer description"], forbiddenSources: ["full market list", "brand audience dump", "multiple unrelated personas"], requirements: ["one decision-maker", "business context", "responsibility"], minWords: 7, maxWords: 48 },
  buyerSituation: { field: "buyerSituation", label: "Buyer situation", purpose: "Describe the customer moment when the current workaround begins to fail.", allowedSources: ["customer pain signals", "current behavior", "campaign topic"], forbiddenSources: ["vendor problem", "campaign creator notes", "offer description"], requirements: ["trigger", "current workaround", "breakdown", "reason it matters now"], minWords: 28, maxWords: 105 },
  coreProblem: { field: "coreProblem", label: "Core problem", purpose: "Explain the customer-side causal obstacle behind the visible symptom.", allowedSources: ["customer pain signals", "buyer context", "marketing reasoning"], forbiddenSources: ["vendor problem", "campaign goal", "desired result", "service description"], requirements: ["causal explanation", "customer perspective", "distinct from buyer situation"], minWords: 16, maxWords: 75 },
  businessConsequence: { field: "businessConsequence", label: "Business consequence", purpose: "Explain what the customer loses, risks, delays, or cannot achieve if the problem continues.", allowedSources: ["core problem", "customer desired outcomes", "business context"], forbiddenSources: ["campaign objective", "vendor problem", "unsupported numbers"], requirements: ["downstream effect", "business relevance", "distinct from core problem"], minWords: 16, maxWords: 75 },
  campaignPointOfView: { field: "campaignPointOfView", label: "Campaign point of view", purpose: "State a distinctive belief about why the familiar approach falls short and what should change.", allowedSources: ["core problem", "internal differentiator", "originality angle", "marketing reasoning"], forbiddenSources: ["generic trust language", "offer description", "unsupported superiority claim"], requirements: ["contrast", "belief", "better approach"], minWords: 18, maxWords: 75 },
  offerExplanation: { field: "offerExplanation", label: "Offer explanation", purpose: "Explain how the resolved promoted offer works and why its mechanism helps.", allowedSources: ["resolved promoted offer", "compatible verified offer facts", "campaign topic"], forbiddenSources: ["ignored offer", "raw saved description", "invented deliverable"], requirements: ["resolved offer", "mechanism", "decision value"], minWords: 22, maxWords: 110 },
  offerDeliverables: { field: "offerDeliverables", label: "Offer deliverables", purpose: "State only what the customer verifiably receives.", allowedSources: ["explicit deliverables", "resolved offer itself"], forbiddenSources: ["inferred report", "invented plan", "implementation promise", "ignored offer"], requirements: ["verified output or honest limitation"], minWords: 8, maxWords: 80 },
  proofAndSupport: { field: "proofAndSupport", label: "Proof and support", purpose: "Use approved evidence only or clearly state that no approved proof was supplied.", allowedSources: ["approved proof"], forbiddenSources: ["knowledge summary", "desired outcome", "invented statistic", "offer promise"], requirements: ["approved evidence or honest no-proof statement"], minWords: 8, maxWords: 100 },
  objectionsAndResponse: { field: "objectionsAndResponse", label: "Objections and response", purpose: "Name one believable customer concern and answer it directly without pressure.", allowedSources: ["customer objections", "creator objections", "verified offer facts"], forbiddenSources: ["fake reassurance", "guarantee", "pressure tactic"], requirements: ["one concern", "one honest response"], minWords: 18, maxWords: 110 },
  messageProgression: { field: "messageProgression", label: "Message progression", purpose: "Define the persuasion sequence from customer moment to one CTA.", allowedSources: ["approved strategy fields"], forbiddenSources: ["new offer", "new proof", "new audience"], requirements: ["situation", "problem", "consequence", "point of view", "offer", "CTA"], minWords: 24, maxWords: 170 },
  primaryCta: { field: "primaryCta", label: "Primary CTA", purpose: "State one concise next action that matches the resolved promoted offer.", allowedSources: ["campaign CTA", "resolved promoted offer"], forbiddenSources: ["secondary action", "ignored offer", "multiple CTAs"], requirements: ["one action", "offer consistency"], minWords: 2, maxWords: 18 },
  contentDirection: { field: "contentDirection", label: "Channel direction", purpose: "Assign a distinct strategic job to every selected channel.", allowedSources: ["selected platforms", "approved strategy"], forbiddenSources: ["new facts", "new offer", "identical channel instructions"], requirements: ["one role per selected channel", "one offer", "one CTA"], minWords: 20, maxWords: 220 },
};

export function formatStrategyFieldContracts() {
  return Object.values(STRATEGY_FIELD_CONTRACTS).map((contract) => `- ${contract.label}: ${contract.purpose} Required: ${contract.requirements.join(", ")}. Allowed sources: ${contract.allowedSources.join(", ")}. Forbidden: ${contract.forbiddenSources.join(", ")}. Length: ${contract.minWords}-${contract.maxWords} words.`).join("\n");
}
